package com.dcms.FrontEndApp;


/**
* FrontEndApp/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Thursday, 19 July, 2018 5:45:17 PM EDT
*/

public interface FrontEndOperations 
{
  String createTRecord (String firstName, String lastName, String address, String phone, String specialization, String location, String managerId);
  String createSRecord (String firstName, String lastName, String coursesRegistered, String status, String statusDate, String managerId);
  String editRecord (String recordID, String fieldName, String newValue, String managerId);
  String getRecordCounts (String managerId);
  String displayRecord (String recordId, String managerId);
  String transferRecord (String managerID, String recordID, String remoteCenterServerName);
} // interface FrontEndOperations
