module FrontEndApp
{
  	interface FrontEnd
  	{
    	string createTRecord(in string firstName, in string lastName, in string address, in string phone, in string specialization, in string location, in string managerId);
		string createSRecord(in string firstName, in string lastName, in string coursesRegistered, in string status, in string statusDate, in string managerId);
		string editRecord(in string recordID, in string fieldName, in string newValue, in string managerId);
		string getRecordCounts(in string managerId);
		string displayRecord(in string recordId, in string managerId);
		string transferRecord(in string managerID, in string recordID, in string remoteCenterServerName) ;
    };
};